global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'game-scores-api'
    static_configs:
      - targets: ['api:8080'] # The target is the 'api' service on its port
