// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"game-scores/ent/game"
	"game-scores/ent/predicate"
	"game-scores/ent/score"
	"game-scores/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScoreUpdate is the builder for updating Score entities.
type ScoreUpdate struct {
	config
	hooks    []Hook
	mutation *ScoreMutation
}

// Where appends a list predicates to the ScoreUpdate builder.
func (su *ScoreUpdate) Where(ps ...predicate.Score) *ScoreUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetValue sets the "value" field.
func (su *ScoreUpdate) SetValue(i int64) *ScoreUpdate {
	su.mutation.ResetValue()
	su.mutation.SetValue(i)
	return su
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (su *ScoreUpdate) SetNillableValue(i *int64) *ScoreUpdate {
	if i != nil {
		su.SetValue(*i)
	}
	return su
}

// AddValue adds i to the "value" field.
func (su *ScoreUpdate) AddValue(i int64) *ScoreUpdate {
	su.mutation.AddValue(i)
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *ScoreUpdate) SetCreatedAt(t time.Time) *ScoreUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *ScoreUpdate) SetNillableCreatedAt(t *time.Time) *ScoreUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// SetUserID sets the "user" edge to the User entity by ID.
func (su *ScoreUpdate) SetUserID(id int) *ScoreUpdate {
	su.mutation.SetUserID(id)
	return su
}

// SetUser sets the "user" edge to the User entity.
func (su *ScoreUpdate) SetUser(u *User) *ScoreUpdate {
	return su.SetUserID(u.ID)
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (su *ScoreUpdate) SetGameID(id int) *ScoreUpdate {
	su.mutation.SetGameID(id)
	return su
}

// SetGame sets the "game" edge to the Game entity.
func (su *ScoreUpdate) SetGame(g *Game) *ScoreUpdate {
	return su.SetGameID(g.ID)
}

// Mutation returns the ScoreMutation object of the builder.
func (su *ScoreUpdate) Mutation() *ScoreMutation {
	return su.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (su *ScoreUpdate) ClearUser() *ScoreUpdate {
	su.mutation.ClearUser()
	return su
}

// ClearGame clears the "game" edge to the Game entity.
func (su *ScoreUpdate) ClearGame() *ScoreUpdate {
	su.mutation.ClearGame()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ScoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ScoreUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ScoreUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ScoreUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *ScoreUpdate) check() error {
	if v, ok := su.mutation.Value(); ok {
		if err := score.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Score.value": %w`, err)}
		}
	}
	if su.mutation.UserCleared() && len(su.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Score.user"`)
	}
	if su.mutation.GameCleared() && len(su.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Score.game"`)
	}
	return nil
}

func (su *ScoreUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(score.Table, score.Columns, sqlgraph.NewFieldSpec(score.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Value(); ok {
		_spec.SetField(score.FieldValue, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedValue(); ok {
		_spec.AddField(score.FieldValue, field.TypeInt64, value)
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(score.FieldCreatedAt, field.TypeTime, value)
	}
	if su.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   score.UserTable,
			Columns: []string{score.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   score.UserTable,
			Columns: []string{score.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   score.GameTable,
			Columns: []string{score.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   score.GameTable,
			Columns: []string{score.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{score.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ScoreUpdateOne is the builder for updating a single Score entity.
type ScoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScoreMutation
}

// SetValue sets the "value" field.
func (suo *ScoreUpdateOne) SetValue(i int64) *ScoreUpdateOne {
	suo.mutation.ResetValue()
	suo.mutation.SetValue(i)
	return suo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (suo *ScoreUpdateOne) SetNillableValue(i *int64) *ScoreUpdateOne {
	if i != nil {
		suo.SetValue(*i)
	}
	return suo
}

// AddValue adds i to the "value" field.
func (suo *ScoreUpdateOne) AddValue(i int64) *ScoreUpdateOne {
	suo.mutation.AddValue(i)
	return suo
}

// SetCreatedAt sets the "created_at" field.
func (suo *ScoreUpdateOne) SetCreatedAt(t time.Time) *ScoreUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *ScoreUpdateOne) SetNillableCreatedAt(t *time.Time) *ScoreUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (suo *ScoreUpdateOne) SetUserID(id int) *ScoreUpdateOne {
	suo.mutation.SetUserID(id)
	return suo
}

// SetUser sets the "user" edge to the User entity.
func (suo *ScoreUpdateOne) SetUser(u *User) *ScoreUpdateOne {
	return suo.SetUserID(u.ID)
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (suo *ScoreUpdateOne) SetGameID(id int) *ScoreUpdateOne {
	suo.mutation.SetGameID(id)
	return suo
}

// SetGame sets the "game" edge to the Game entity.
func (suo *ScoreUpdateOne) SetGame(g *Game) *ScoreUpdateOne {
	return suo.SetGameID(g.ID)
}

// Mutation returns the ScoreMutation object of the builder.
func (suo *ScoreUpdateOne) Mutation() *ScoreMutation {
	return suo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (suo *ScoreUpdateOne) ClearUser() *ScoreUpdateOne {
	suo.mutation.ClearUser()
	return suo
}

// ClearGame clears the "game" edge to the Game entity.
func (suo *ScoreUpdateOne) ClearGame() *ScoreUpdateOne {
	suo.mutation.ClearGame()
	return suo
}

// Where appends a list predicates to the ScoreUpdate builder.
func (suo *ScoreUpdateOne) Where(ps ...predicate.Score) *ScoreUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ScoreUpdateOne) Select(field string, fields ...string) *ScoreUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Score entity.
func (suo *ScoreUpdateOne) Save(ctx context.Context) (*Score, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ScoreUpdateOne) SaveX(ctx context.Context) *Score {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ScoreUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ScoreUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *ScoreUpdateOne) check() error {
	if v, ok := suo.mutation.Value(); ok {
		if err := score.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Score.value": %w`, err)}
		}
	}
	if suo.mutation.UserCleared() && len(suo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Score.user"`)
	}
	if suo.mutation.GameCleared() && len(suo.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Score.game"`)
	}
	return nil
}

func (suo *ScoreUpdateOne) sqlSave(ctx context.Context) (_node *Score, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(score.Table, score.Columns, sqlgraph.NewFieldSpec(score.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Score.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, score.FieldID)
		for _, f := range fields {
			if !score.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != score.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Value(); ok {
		_spec.SetField(score.FieldValue, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedValue(); ok {
		_spec.AddField(score.FieldValue, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(score.FieldCreatedAt, field.TypeTime, value)
	}
	if suo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   score.UserTable,
			Columns: []string{score.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   score.UserTable,
			Columns: []string{score.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   score.GameTable,
			Columns: []string{score.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   score.GameTable,
			Columns: []string{score.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Score{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{score.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
