{
 "title": "GameScores API",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests Per Minute (RPM)",
   "type": "stat",
   "description": "Total Requests Per Minute (RPS) of the last 5 min",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1h])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "stat",
   "description": "The response time that 95% of users are experiencing. ",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Error Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Code Distribution",
   "type": "piechart",
   "description": "Response codes breakdown",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[1h])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 APIs (Requests per minute)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (rate(http_requests_total[10m]))) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Per Second per Endpoint",
   "type": "timeseries",
   "description": "Requests per second for each API route",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}